# Generated by Django 4.1 on 2023-05-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
